services:
  postgres:
    image: postgres:16
    container_name: sago-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sago_reengage
    ports:
      - "5432:5432"
    volumes:
      - sago_postgres_data:/var/lib/postgresql/data
volumes:
  sago_postgres_data:
